return {
    --[ Ran
    ["Blood"] = {{"BloodBag", 50}},
    ["Pk"] = {{"Painkillers", 50}},
    ["Food"] = {{"MRE", 25}, {"WaterBottle", 25}},
    ["Gadgets"] = {"Watch", "Compass", "Map", "GPS", "OmniLight", "Radio", "Matches", "Binoculars", "Detonator", "Entrencher", "Katana", "Knife", "Hatchet", "Sabre", "GreenChemlight", "RedChemlight", "BlueChemlight", "FlashlightSurvival", "FlashlightOld", "FlashlightMilitary"},
    ["Car"] = {{"JerryCan", 2}, {"ReinforcedWheel", 6}, "EngineParts", "ScrapMetal", "FuelTank", "ArmorPlates", "BallisticGlass"},
    ["Base"] = {{"Material1", 5}, {"Material2", 5}, {"Material3", 5}, {"Material4", 5}, {"Material5", 5}, {"Material6", 5}, {"Material7", 5}, {"Floodlight", 5}, {"LargeCrate", 5}, {"SmallCrate", 5}},
    --[ Clothes
    ["SpecOps"] = {"BallisticSpecOps", "BandanaBlack", "CamoSpecialTop", "CamoSpecialBottom"},
    ["GusArmor"] = {"GusArmorTop", "GusArmorBottom"},
    ["KethArmor"] = {"KethArmorTop", "KethArmorBottom"},
    --[ Ran Guns
    ["Mk48=1"] = {"HikingPackWhite", "Mk 48", {"FedorovAmmo", 7}, {"BloodBag", 9}, "Painkillers", "ACOG", "Grip"},
    ["Mk48=2"] = {"MilitaryPackBlack", "Mk 48", {"FedorovAmmo", 9}, {"BloodBag", 11}, "Painkillers", "ACOG", "Grip"},
    ["M249=1"] = {"HikingPackWhite", "M249", {"M249Ammo100", 7}, {"BloodBag", 9}, "Painkillers", "ACOG", "Grip"},
    ["M249=2"] = {"MilitaryPackBlack", "M249", {"M249Ammo100", 9}, {"BloodBag", 11}, "Painkillers", "ACOG", "Grip", "Suppressor9"},
    ["MP5=1"] = {"HikingPackWhite", "MP5", {"MP5Ammo", 7}, {"BloodBag", 8}, "Painkillers", "ACOG", "Grip", "Suppressor9"},
    ["MP5=2"] = {"MilitaryPackBlack", "MP5", {"MP5Ammo", 9}, {"BloodBag", 10}, "Painkillers", "ACOG", "Grip"},
    ["Fedorov=1"] = {"HikingPackWhite", "Fedorov", {"FedorovAmmo", 7}, {"BloodBag", 9}, "Painkillers"},
    ["Fedorov=2"] = {"MilitaryPackBlack", "Fedorov", {"FedorovAmmo", 9}, {"BloodBag", 11}, "Painkillers"},
    ["PP19=1"] = {"HikingPackWhite", "PP-19", {"PP19Ammo64", 7}, {"BloodBag", 9}, "Painkillers", "ACOG", "Suppressor9"},
    ["PP19=2"] = {"MilitaryPackBlack", "PP-19", {"PP19Ammo64", 9}, {"BloodBag", 11}, "Painkillers", "ACOG", "Suppressor9"},
    ["PPSH=1"] = {"HikingPackWhite", "PPSH", {"PPSHAmmo", 7}, {"BloodBag", 9}, "Painkillers"},
    ["PPSH=2"] = {"MilitaryPackBlack", "PPSH", {"PPSHAmmo", 9}, {"BloodBag", 11}, "Painkillers"},
    --[ Battle Rifles
    ["M14=1"] = {"HikingPackWhite", "M14", {"M14Ammo50", 7}, {"BloodBag", 8}, "Painkillers", "ACOG", "Grip", "Suppressor762"},
    ["FAL=1"] = {"HikingPackWhite", "FAL", {"M14Ammo50", 7}, {"BloodBag", 8}, "Painkillers", "ACOG", "Grip", "Suppressor762"},
    ["Mk17=1"] = {"HikingPackWhite", "Mk 17", {"M14Ammo50", 7}, {"BloodBag", 8}, "Painkillers", "ACOG", "Grip", "Suppressor762"},
    ["HK21=1"] = {"HikingPackWhite", "HK21", {"M14Ammo50", 7}, {"BloodBag", 8}, "Painkillers", "ACOG", "Grip", "Suppressor762"},
    ["HK417=1"] = {"HikingPackWhite", "HK417", {"M14Ammo50", 7}, {"BloodBag", 8}, "Painkillers", "ACOG", "Grip", "Suppressor762"},
    ["G3=1"] = {"HikingPackWhite", "G3", {"M14Ammo50", 7}, {"BloodBag", 8}, "Painkillers", "ACOG", "Grip", "Suppressor762"},
    ["M14=2"] = {"MilitaryPackBlack", "M14", {"M14Ammo50", 9}, {"BloodBag", 10}, "Painkillers", "ACOG", "Grip", "Suppressor762"},
    ["FAL=2"] = {"MilitaryPackBlack", "FAL", {"M14Ammo50", 9}, {"BloodBag", 10}, "Painkillers", "ACOG", "Grip", "Suppressor762"},
    ["Mk17=2"] = {"MilitaryPackBlack", "Mk 17", {"M14Ammo50", 9}, {"BloodBag", 10}, "Painkillers", "ACOG", "Grip", "Suppressor762"},
    ["HK21=2"] = {"MilitaryPackBlack", "HK21", {"M14Ammo50", 9}, {"BloodBag", 10}, "Painkillers", "ACOG", "Grip", "Suppressor762"},
    ["HK417=2"] = {"MilitaryPackBlack", "HK417", {"M14Ammo50", 9}, {"BloodBag", 10}, "Painkillers", "ACOG", "Grip", "Suppressor762"},
    ["G3=2"] = {"MilitaryPackBlack", "G3", {"M14Ammo50", 9}, {"BloodBag", 10}, "Painkillers", "ACOG", "Grip", "Suppressor762"},
    --[ STANAG ARs
    ["Pat=1"] = {"HikingPackWhite", "Patriot", {"STANAGAmmo100", 7}, {"BloodBag", 8}, "Painkillers", "ACOG", "Grip", "Suppressor556"},
    ["G36k=1"] = {"HikingPackWhite", "G36k", {"STANAGAmmo100", 7}, {"BloodBag", 8}, "Painkillers", "ACOG", "Grip", "Suppressor556"},
    ["M4A1=1"] = {"HikingPackWhite", "M4A1", {"STANAGAmmo100", 7}, {"BloodBag", 8}, "Painkillers", "ACOG", "Grip", "Suppressor556"},
    ["SCAR=1"] = {"HikingPackWhite", "SCAR-L", {"STANAGAmmo100", 7}, {"BloodBag", 8}, "Painkillers", "ACOG", "Grip", "Suppressor556"},
    ["Pat=2"] = {"MilitaryPackBlack", "Patriot", {"STANAGAmmo100", 9}, {"BloodBag", 10}, "Painkillers", "ACOG", "Grip", "Suppressor556"},
    ["G36k=2"] = {"MilitaryPackBlack", "G36k", {"STANAGAmmo100", 9}, {"BloodBag", 10}, "Painkillers", "ACOG", "Grip", "Suppressor556"},
    ["M4A1=2"] = {"MilitaryPackBlack", "M4A1", {"STANAGAmmo100", 9}, {"BloodBag", 10}, "Painkillers", "ACOG", "Grip", "Suppressor556"},
    ["SCAR=2"] = {"MilitaryPackBlack", "SCAR-L", {"STANAGAmmo100", 9}, {"BloodBag", 10}, "Painkillers", "ACOG", "Grip", "Suppressor556"},
    --[ Black AKs
    ["Ak12=1"] = {"HikingPackWhite", "AK-12", {"AK47Ammo75", 7}, {"BloodBag", 8}, "Painkillers", "ACOG", "Grip", "Suppressor762"},
    ["AK104=1"] = {"HikingPackWhite", "AK-104", {"AK47Ammo75", 7}, {"BloodBag", 8}, "Painkillers", "ACOG", "Grip", "Suppressor762"},
    ["OTs14=1"] = {"HikingPackWhite", "OTs-14", {"AK47Ammo75", 7}, {"BloodBag", 8}, "Painkillers", "ACOG", "Suppressor762"},
    ["AK47=1"] = {"HikingPackWhite", "AK-47", {"AK47Ammo75", 7}, {"BloodBag", 8}, "Painkillers", "ACOG", "Suppressor762"},
    ["RPK=1"] = {"HikingPackWhite", "RPK", {"AK47Ammo75", 7}, {"BloodBag", 8}, "Painkillers", "ACOG", "Suppressor762"},
    ["AKM=1"] = {"HikingPackWhite", "AKM", {"AK47Ammo75", 7}, {"BloodBag", 8}, "Painkillers", "ACOG", "Suppressor762"},
    ["Ak12=2"] = {"MilitaryPackBlack", "AK-12", {"AK47Ammo75", 9}, {"BloodBag", 10}, "Painkillers", "ACOG", "Grip", "Suppressor762"},
    ["AK104=2"] = {"MilitaryPackBlack", "AK-104", {"AK47Ammo75", 9}, {"BloodBag", 10}, "Painkillers", "ACOG", "Grip", "Suppressor762"},
    ["OTs14=2"] = {"MilitaryPackBlack", "OTs-14", {"AK47Ammo75", 9}, {"BloodBag", 10}, "Painkillers", "ACOG", "Suppressor762"},
    ["AK47=2"] = {"MilitaryPackBlack", "AK-47", {"AK47Ammo75", 9}, {"BloodBag", 10}, "Painkillers", "ACOG", "Suppressor762"},
    ["RPK=2"] = {"MilitaryPackBlack", "RPK", {"AK47Ammo75", 9}, {"BloodBag", 10}, "Painkillers", "ACOG", "Suppressor762"},
    ["AKM=2"] = {"MilitaryPackBlack", "AKM", {"AK47Ammo75", 9}, {"BloodBag", 10}, "Painkillers", "ACOG", "Suppressor762"}
};