return {
    ["Snow"] = {
        "SnowOnTop",
        "Get Snow Now For Free!",
        "Demolish Servers With Snow",
        "Imaging Paying For Cheats",
        "The Owner Of Snow Is Gonna Flood You",
        "Come Join Snow At hvW8XeXyQy",
        "SnowOnTop 🔥🔥",
        "$10 Just To Be OutDone By $0",
        "Best Free HvH Script",
        "Flooded0 Is Actually A Co-Owner Of AR2",
        "Imagine Not Getting Hacks In A Block Game",
        "Snow Is So Cool, You Should Get It For Free!",
        "Instead Of Sweating, You Should Chill With Snow",
        "You Just Got Frozen By Snow",
        "You Just Got Dunked On By Snow",
        "Why Isn't The AntiCheat Working? Can Someone Help Me",
        "🥶🥶🥶🥶🥶",
        "❄❄SnowOnTop❄❄",
        "Crushed So Hard You Just Got Frozen Solid By Snow",
        "Took The L By Snow"
    },
    ["TrashTalk"] = {
        "L",
        "GG Ez",
        "Playing Legit Is Lame",
        "Im Actually A Beta Tester",
        "AntiCheat Isn't Even Working, Whats Going On Hear???",
        "Dunked On",
        "Frozen Solid",
        "Cope, Pray & Hope",
        "Suck It",
        "Retard",
        "Cat CatFood",
        "Lemme Sprinkle Some Salt On You",
        "Take The L",
        "Heres Your L For $0",
    },
    ["Emojis"] = {}
};